// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxjaffnysitulaojvscz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4amFmZm55c2l0dWxhb2p2c2N6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg2NzcyMTksImV4cCI6MjA4NDI1MzIxOX0.ZHvrwshQQRiW9IEN_XEfuQHlUoFWn7rAR3MMidOctFg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});